# Generated by Django 2.0.2 on 2018-03-14 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=200)),
                ('PhoneNumber', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'StudentDetail',
            },
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Java', models.IntegerField()),
                ('CSharp', models.IntegerField()),
                ('Angular', models.IntegerField()),
                ('Node', models.IntegerField()),
                ('Python', models.IntegerField()),
                ('TotalMarks', models.IntegerField(max_length=3)),
                ('StudentDetailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminInfo.StudentDetail')),
            ],
            options={
                'verbose_name_plural': 'SubjectDetail',
            },
        ),
    ]
